name: Build and Deploy Workflow
on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Install and Run Trivy for FS Scan
        run: >
          # Install dependencies

          sudo apt-get update

          sudo apt-get install -y wget apt-transport-https gnupg lsb-release


          # Add Trivy GPG key and repository

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list


          # Update package list and install Trivy

          sudo apt-get update

          sudo apt-get install -y trivy


          # Scan the current directory

          trivy fs .
